SQLALCHEMY_DATABASE_URI = 'sqlite:///flaskr.db'
SECRET_KEY = 'secret key'
JSON_AS_ASCII = False
JSON_SORT_KEYS = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
CORS_HEADERS = 'Content-Type'
ACCESS_CONTROL_ALLOW_ORIGIN = '*'
